### PR TITLE
sharing some (unfinished) latex docs

### PR DESCRIPTION
**Pull request by jberthold**

### CODE REVIEW

**Comment by jberthold** [comment]
Hi, who has got write access here? Trying to share my (mostly unfinished) latex 
\cc @mjhopkins @rowandavies

**Comment by mjhopkins** [comment]
Maybe check in the pdf too?

Otherwise LGTM.

**Comment by mjhopkins** [comment]
Merged.

**Comment by jberthold** [comment]
Thanks Mark...
I was actually in the middle of writing more on the syntax page. Will push that another time

**Pull request closed without merging**
